version: "3"

services:
  server:
    build: ./server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./server:/go/src/app
    command: sh -c "go build . && ./app"
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - server
    ports:
      - 80:80